### ISSUE TITLE
patch的方式

### ISSUE THREAD

**Issue by ITCJ** [wklchris/Rime-latex-symbols#2]
我在 `double_pinyin_flypy.schema.yaml` 尝试使用
```
patch:
  punctuator/import_preset: latexmath
  recognizer/patterns:
    punct: "^/([0-9]0?|[A-Za-z]+)$"
```
无效，随后直接在`punctuator`的最后添加` import_preset: latexmath`后生效
```
punctuator:
  import_preset: symbols
  # 定义部分半角字符
  half_shape:
      "#": "#"
      "*": "*"
      '.' : { commit: 。 }
      "`": "`"
      "~": "~"
      "@": "@"
      "=": "="
      "/": ["/", "÷",]
      '\': "、"
      "_" : "──"
      "'": {pair: ["「", "」"]}
      "[": ["【", "["]
      "]": ["】", "]"]
      "$": ["¥", "$", "€", "£", "¢", "¤"]
      "<": ["《", "〈", "«", "<"]
      ">": ["》", "〉", "»", ">"]
  import_preset: latexmath
```
请问这是啥原因
